### ISSUE TITLE
Feature request: .array()

### ISSUE THREAD

**Issue by samuelmn3** [apple/swift-cassandra-client#24]
Hi,
I would need `.array()` feature in order to inject String array with IN clause.
Is there an alternative in the meantime ?

**Comment by yim-lee** [comment]
You can see if any of the [`CassandraSession.query` variants](https://github.com/apple/swift-cassandra-client/blob/main/Sources/CassandraClient/Session.swift#L117) suits your needs.

Otherwise, at quick glance, this will require adding `.stringArray([String])` (and potentially other types) to `Statement.Value`. We will need to use `cass_collection_append_*` to build up a collection then pass it to `cass_statement_bind_collection`, as shown in the code below ([source](https://blog.csdn.net/weixin_33736832/article/details/90096271)):

<img width="824" alt="image" src="https://github.com/apple/swift-cassandra-client/assets/12647725/2292f888-55d8-40fa-bcab-9a5c5d332c32">
